name: "Hello World Composite Action"
description: "A composite action that prints Hello World and runs another action"
author: "your-name"

runs:
  using: "composite"
  steps:
    - name: Run another action (checkout)
      uses: TESTORGs3rdz0tests/testaction1@main

